#!/usr/bin/env bash
# Configure Nginx with custom HTTP header

# Update and install Nginx
sudo apt update -y
sudo apt install nginx -y

# code to add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# If the test is successful, restart Nginx
if [ $? -eq 0 ]; then
    sudo service nginx restart
    echo "Nginx configuration updated and restarted successfully."
else
    echo "Nginx configuration test failed. Please check the configuration."
    exit 1
fi