#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "This is Oreste from Holberton School :)" > /var/www/html/index.html
sudo service nginx start
